### PR TITLE
Added instructions for building the project.

### PR DESCRIPTION
**Pull request by KamranMackey**

### CODE REVIEW

**Comment by chylex** [comment]
That's the same instructions as for any other ForgeGradle project, don't really see the point of having it here.

**Comment by KamranMackey** [comment]
@chylex I do. It's really useful for people who don't want to have to go to another repository to find the build instructions.

**Comment by chylex** [comment]
You get the instructions when you download Forge src, which you need to do anyways because I don't ship gradle.

**Comment by KamranMackey** [comment]
@chylex Yeah I know, but you could still merge my PR anyway, because my PR is still useful.

**Comment by chylex** [comment]
Is it really that difficult to remember two commands? :/ I don't expect people with no modding background to try and do something with the project. It'd need to be changed anyways, because it won't work for windows unless you have gradle installed instead of just using the wrapper.

**Comment by chylex** [comment]
Actually I don't ship gradle, so that would need to be included in the build instructions too... bit of a mess here :P everyone seems to have figured it out though, so I didn't get any complaints on what to do with it. Idk...

**Comment by chylex** [comment]
Added the instructions.

**Pull request closed without merging**
