### PR TITLE
Fixes for DragonChunkManager

### PR DESCRIPTION
**Pull request by LakMoore**
Updated references to use singleton instance
Stripped unnecessary code for making expensive checks (every 4 pings) for chunks that need adding or removing from the ForgeChunkManager (ForgeChunkManager will do this anyway) 
ChunkListDepth is currently set to 9 there is a potential case (if loading and unloading chunks is expensive) for increasing this buffer size

[With this attached change my HEE experience went from 5 fps to >30 fps]

### CODE REVIEW

**Comment by chylex** [comment]
Thanks, I'll get to work on a minor update of HEE in a couple days so I'll review the PR then. This was my first time working with chunk loaders, had no idea the code had such a major hit on framerate :/.

**Comment by LakMoore** [comment]
I haven't done any work with chunk loaders and I think I would have done exactly the same as you.  But my framerate died and I wanted to find the cause.  Also I have removed Optifine from my set up so I can no longer say that your code was 100% to blame for my poor FPS.

Great job with HEE... I haven't killed the dragon since! :-)

**Comment by chylex** [comment]
I won't have internet connection for a short while but I'll grab the commit and try to check everything tomorrow.

**Comment by chylex** [comment]
Can't reopen the PR after renaming the branch, I'll cherry-pick the commit and try to merge it that way.

**Comment by chylex** [comment]
Eh got a bad revision error. If you make a PR to a non-master branch, does it add you to the contributor list? Cause I could just add the changes manually but I want you to be in the contributor list, however I'm not sure if it would do that since it's not against master.

I guess if you want, you can try making a new PR against the HEE1-1.7.10 branch. I think **it should be possible to just use your old branch and compare against the new one**, but if not and if switching branches doesn't work because of the commit, this _should_ do it:

```
# Revert last commit
git show HEAD > patch
git revert HEAD
git apply patch

# Stash the changes
git stash

# Switch branch
git fetch origin
git checkout -b HEE1-1.7.10 origin/HEE1-1.7.10

# Reapply changes
git stash apply
```

**Comment by chylex** [comment]
Ok according to [GitHub help](https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/), PRs towards non-master branch don't count as contributions, so I'll merge it manually. Master is for development so HEE 1 commits won't be merged into it.

**Comment by LakMoore** [comment]
Thanks for trying to get my name in lights.  If it works, great!  If not, progress of the mod is all that matters! :-) How very magnanimous of me! :-)

Anyway... I didn't think you needed to track prevChunkXZ because the ForgeChunkManager will be making the exact same checks anyway.

I have played in the End for quite a while with my version of the code and haven't run into any problems.  I will update my code to yours with the next release.

I did think, some little time later, would it not be easier just to keep the whole centre island loaded?  I do not know how far the dragon ventures from (0,0) but if that information is known and that number of chunks is small it MIGHT be more efficient to keep those loaded rather than constantly loading and unloading chunks as the dragon moves around.  This is pure guesswork and you will know better than me.

Also, I did notice that the Dragon's fireballs freeze as they try to move into unloaded chunks.  Perhaps that needs opening in an issue of its own but the solution might be to make them have a limited range? If they are on a path out of the loaded chunks (because the player is flying) they are unlikely to hit the main island anyway!

Cheers

Lak

**Comment by chylex** [comment]
The default limit is 25 chunks per ticket, plus some additional limits on total amount of chunks that can be loaded - the main island would require about at least 5 times that. Fireball unloading is kinda crap but they get destroyed on load.

In HEE 2, I'm taking over just about everything about the End code-wise, so I will look into implementing custom full territory chunk loading for boss areas.

https://hee.chylex.com/credits

**Pull request closed without merging**
