### PR TITLE
[FIXED] Change file encoding of mcmod.info to UTF-8

### PR DESCRIPTION
**Pull request by Holi0317**
Using non-unicode encoding causes some symbol cannot be displayed.
latin1
2015-09-05-18 21 08-screenshot

### CODE REVIEW

**Comment by chylex** [comment]
The problem is that now it doesn't render correctly on Windows systems. What system do you have and what happens if you use US-ASCII or ISO-8859-1?

**Comment by Holi0317** [comment]
I am on Arch Linux.

Changing my LANG to 'en_US.iso88591' does not help. Still having the same issue.

This is the output of `locale`. This does changes my locale to ASCII?
```
LANG=en_US.iso88591
LC_CTYPE=zh_TW.UTF-8
LC_NUMERIC=zh_TW.UTF-8
LC_TIME=zh_TW.UTF-8
LC_COLLATE="en_US.iso88591"
LC_MONETARY=zh_TW.UTF-8
LC_MESSAGES="en_US.iso88591"
LC_PAPER=zh_TW.UTF-8
LC_NAME="en_US.iso88591"
LC_ADDRESS="en_US.iso88591"
LC_TELEPHONE="en_US.iso88591"
LC_MEASUREMENT=zh_TW.UTF-8
LC_IDENTIFICATION="en_US.iso88591"
LC_ALL=
```

**Comment by chylex** [comment]
Not familiar with linux, so I can't really say what it's trying to load the file from. I have ubuntu setup on another computer, I can get it and test it there in about 2 days.

**Comment by Holi0317** [comment]
Just tested this on a clean lubuntu with openjdk8 and MultiMC. And the bug is still there

**Comment by Holi0317** [comment]
I think this is a forge bug. As forge did not specify the encoding of FileReader and java uses different encoding according to platform.

**Comment by chylex** [comment]
I don't think 1.7.10 is getting any more updates, but it might still be worth letting @cpw know. I'll see if I can replace the characters in the code or something.

**Comment by chylex** [comment]
The description formatting is now modified in code, so it should work on all systems. Don't know if I'm going to be releasing another 1.x bugfix update, but it'll be in 2.0 at least.

**Pull request closed without merging**
